import { useState } from 'react'
import { Button, ButtonGroup } from 'react-bootstrap'

// Code generation panel: shows the PID algorithm as pseudocode or an Arduino
// sketch with the current slider values substituted live. Tutorial `highlight`
// keys cause matching value spans to glow so students see slider ↔ code.

// ── primitive renderers ──────────────────────────────────────────────────────

function L({ children }) {
  return <div className="cl">{children ?? ' '}</div>
}

function V({ children, hl }) {
  return <span className={`cv${hl ? ' cv-hl' : ''}`}>{children}</span>
}

function C({ children }) {
  return <span className="cc">{children}</span>
}

function K({ children }) {
  return <span className="ck">{children}</span>
}

// ── pseudocode view ──────────────────────────────────────────────────────────

function PseudoCode({ kp, ki, kd, base, ts, platform, sensorCount, highlight = [] }) {
  const [lo, hi] = platform?.motor_speed_range || [0, 255]
  const spacing  = platform?.sensor_spacing_mm  || 12
  const center   = ((sensorCount - 1) / 2).toFixed(1)
  const Ts       = (ts / 1000).toFixed(3)
  const hl       = (k) => highlight.includes(k)

  return (
    <div className="code-block">
      <L>── SETUP ──────────────────────────────────────────</L>
      <L>{'  '}Kp = <V hl={hl('kp')}>{kp}</V>{'   '}Ki = <V hl={hl('ki')}>{ki}</V>{'   '}Kd = <V hl={hl('kd')}>{kd}</V></L>
      <L>{'  '}base_speed = <V hl={hl('base')}>{base}</V>{'   '}Ts = <V hl={hl('ts')}>{ts}</V> ms</L>
      <L>{'  '}last_error = 0 ;  integral = 0</L>
      <L />
      <L>── EVERY <V hl={hl('ts')}>{ts}</V> ms ──────────────────────────────────</L>
      <L>{'  '}position   = read_sensors(){'   '}<C>// {sensorCount} sensors, {spacing} mm apart</C></L>
      <L>{'  '}error      = position − <V>{center}</V>{'   '}<C>// centre = ({sensorCount}−1)/2</C></L>
      <L />
      <L>{'  '}<K>if</K> all sensors off line:</L>
      <L>{'      '}error ← hold last extreme{'   '}<C>// steer toward where line vanished</C></L>
      <L />
      <L>{'  '}integral   ← integral + error × <V>{Ts}</V></L>
      <L>{'  '}derivative ← (error − last_error) / <V>{Ts}</V></L>
      <L />
      <L>{'  '}output = Kp × error  +  Ki × integral  +  Kd × derivative</L>
      <L>{'         ='} <V hl={hl('kp')}>{kp}</V> × error{'  +  '}<V hl={hl('ki')}>{ki}</V> × integral{'  +  '}<V hl={hl('kd')}>{kd}</V> × derivative</L>
      <L>{'              ↑ P-term         ↑ I-term          ↑ D-term'}</L>
      <L />
      <L>{'  '}left_motor  ← clamp(<V hl={hl('base')}>{base}</V> − output,  <V>{lo}</V>, <V>{hi}</V>)</L>
      <L>{'  '}right_motor ← clamp(<V hl={hl('base')}>{base}</V> + output,  <V>{lo}</V>, <V>{hi}</V>)</L>
      <L />
      <L>{'  '}last_error ← error</L>
    </div>
  )
}

// ── Arduino C++ view ─────────────────────────────────────────────────────────

function ArduinoCode({ kp, ki, kd, base, ts, platform, sensorCount }) {
  const [lo, hi] = platform?.motor_speed_range || [0, 255]
  const centerF   = ((sensorCount - 1) / 2).toFixed(1)
  const posMax    = (sensorCount - 1) * 1000
  const name      = platform?.name || 'ESP32 QTR-8RC'

  const code = `\
// PID Line Follower — generated by Matamoe PID Simulator
// Platform: ${name}
// Tune values in the simulator, then paste here.

#include <QTRSensors.h>

#define KP          ${kp}f
#define KI          ${ki}f
#define KD          ${kd}f
#define BASE_SPEED  ${base}
#define TS_MS       ${ts}

QTRSensors qtr;
const uint8_t NUM_SENSORS = ${sensorCount};
uint16_t sensorValues[NUM_SENSORS];

float lastError = 0, integral = 0;

void setup() {
  qtr.setTypeRC();
  // TODO: set your sensor GPIO pins
  // qtr.setSensorPins((const uint8_t[]){2,4,5,12,13,14,15,16}, NUM_SENSORS);
  qtr.calibrate();
}

void loop() {
  uint16_t pos = qtr.readLineBlack(sensorValues);  // 0 .. ${posMax}
  float error  = (float)pos / 1000.0f - ${centerF}f;

  integral  += error * (TS_MS * 0.001f);
  float deriv = (error - lastError) / (TS_MS * 0.001f);

  float output = KP * error + KI * integral + KD * deriv;

  int leftSpeed  = constrain(BASE_SPEED - (int)output, ${lo}, ${hi});
  int rightSpeed = constrain(BASE_SPEED + (int)output, ${lo}, ${hi});

  // TODO: replace with your motor driver
  // driveMotors(leftSpeed, rightSpeed);

  lastError = error;
  delay(TS_MS);
}`

  return <pre className="code-block arduino-code">{code}</pre>
}

// ── MicroPython stub ─────────────────────────────────────────────────────────

function MicroPythonCode({ kp, ki, kd, base, ts, sensorCount }) {
  const centerF = ((sensorCount - 1) / 2).toFixed(1)

  const code = `\
# PID Line Follower — generated by Matamoe PID Simulator
# Tune in the simulator, then paste here.

KP, KI, KD   = ${kp}, ${ki}, ${kd}
BASE_SPEED    = ${base}
TS_MS         = ${ts}
NUM_SENSORS   = ${sensorCount}

last_error = 0
integral   = 0

def read_error():
    """Return weighted position error (−${centerF} .. +${centerF})."""
    # TODO: read your sensor array and return weighted average
    raise NotImplementedError

def drive(left, right):
    """Set motor speeds (0..255)."""
    # TODO: call your motor driver
    pass

while True:
    error = read_error()
    integral  += error * (TS_MS / 1000)
    deriv      = (error - last_error) / (TS_MS / 1000)
    output     = KP * error + KI * integral + KD * deriv
    left_spd   = max(0, min(255, BASE_SPEED - int(output)))
    right_spd  = max(0, min(255, BASE_SPEED + int(output)))
    drive(left_spd, right_spd)
    last_error = error
    time.sleep_ms(TS_MS)`

  return <pre className="code-block arduino-code">{code}</pre>
}

// ── copy helper ───────────────────────────────────────────────────────────────

function CopyBtn({ getText }) {
  const [done, setDone] = useState(false)
  const copy = () => {
    navigator.clipboard.writeText(getText()).then(() => {
      setDone(true)
      setTimeout(() => setDone(false), 1500)
    })
  }
  return (
    <Button size="sm" variant="outline-secondary" onClick={copy}>
      {done ? '✓ Copied' : 'Copy'}
    </Button>
  )
}

// ── public component ──────────────────────────────────────────────────────────

const TABS = ['Pseudocode', 'Arduino C++', 'MicroPython']

export default function CodePanel({ kp, ki, kd, base, ts, platform, sensorCount, highlight = [] }) {
  const [tab, setTab] = useState(0)

  const pseudoText = () => {
    const [lo, hi] = platform?.motor_speed_range || [0, 255]
    const spacing  = platform?.sensor_spacing_mm  || 12
    const center   = ((sensorCount - 1) / 2).toFixed(1)
    const Ts       = (ts / 1000).toFixed(3)
    return [
      `── SETUP ──────────────────────────────────────────`,
      `  Kp = ${kp}   Ki = ${ki}   Kd = ${kd}`,
      `  base_speed = ${base}   Ts = ${ts} ms`,
      `  last_error = 0 ;  integral = 0`,
      ``,
      `── EVERY ${ts} ms ──────────────────────────────────`,
      `  position   = read_sensors()   // ${sensorCount} sensors, ${spacing} mm apart`,
      `  error      = position − ${center}   // centre = (${sensorCount}−1)/2`,
      ``,
      `  if all sensors off line:`,
      `      error ← hold last extreme   // steer toward where line vanished`,
      ``,
      `  integral   ← integral + error × ${Ts}`,
      `  derivative ← (error − last_error) / ${Ts}`,
      ``,
      `  output = Kp × error  +  Ki × integral  +  Kd × derivative`,
      `         = ${kp} × error  +  ${ki} × integral  +  ${kd} × derivative`,
      `              ↑ P-term         ↑ I-term          ↑ D-term`,
      ``,
      `  left_motor  ← clamp(${base} − output,  ${lo}, ${hi})`,
      `  right_motor ← clamp(${base} + output,  ${lo}, ${hi})`,
      ``,
      `  last_error ← error`,
    ].join('\n')
  }

  return (
    <div className="code-panel">
      <div className="d-flex justify-content-between align-items-center mb-2">
        <ButtonGroup size="sm">
          {TABS.map((t, i) => (
            <Button key={t} variant={tab === i ? 'primary' : 'outline-secondary'}
              onClick={() => setTab(i)}>{t}</Button>
          ))}
        </ButtonGroup>
        {tab === 0 && <CopyBtn getText={pseudoText} />}
      </div>

      {tab === 0 && (
        <PseudoCode kp={kp} ki={ki} kd={kd} base={base} ts={ts}
          platform={platform} sensorCount={sensorCount} highlight={highlight} />
      )}
      {tab === 1 && (
        <ArduinoCode kp={kp} ki={ki} kd={kd} base={base} ts={ts}
          platform={platform} sensorCount={sensorCount} />
      )}
      {tab === 2 && (
        <MicroPythonCode kp={kp} ki={ki} kd={kd} base={base} ts={ts}
          sensorCount={sensorCount} />
      )}
    </div>
  )
}
