// Guided PID teaching progression.
// Each lesson has: a suggested `setup` (applied by the button), `highlight`
// keys (ring the relevant controls), a short `goal`, and `steps` — a
// checklist students tick off manually as they work through the activity.

export const LESSONS = [
  {
    id: 'start-slow',
    title: '1 · Start slow — no steering',
    goal: 'See what happens when the robot has no way to correct itself.',
    body: 'With Kp = 0 the PID output is always zero — the robot drives at a fixed speed with no correction at all. This is your baseline.',
    steps: [
      'Click "Apply setup" then press Start.',
      'Watch the robot drift off the straight line — it cannot correct itself.',
      'Open the Code panel and find the output formula. What is 0 × error?',
      'Nudge Kp to 1 or 2 on the slider. Can you see a difference?',
    ],
    setup: { track: 'straight', kp: 0, ki: 0, kd: 0, base: 50 },
    highlight: ['kp'],
  },
  {
    id: 'add-p',
    title: '2 · Add P — the spring',
    goal: 'Understand how Kp pulls the robot back to the centre line.',
    body: 'Kp acts like a spring: the further the robot is from the line, the harder it pulls. A small Kp barely corrects; a large one corrects quickly — but may overshoot.',
    steps: [
      'Apply setup (Kp = 20), press Start on the straight track.',
      'Watch the robot snap back to the line — P-term is working.',
      'Raise Kp to 40, reset and run — it corrects faster. Watch the P-term graph.',
      'Raise Kp to 60 — does it still track cleanly or does it wobble?',
      'Find the highest Kp that stays smooth on a straight. Note the value.',
    ],
    setup: { track: 'straight', kp: 20, ki: 0, kd: 0, base: 80 },
    highlight: ['kp'],
  },
  {
    id: 'oscillation',
    title: '3 · Too much spring — oscillation',
    goal: 'See how a high Kp causes the robot to zigzag uncontrollably.',
    body: 'On a curve, a strong spring snaps the robot back too hard so it overshoots the line — then snaps back again. The Error graph swings back and forth. This is oscillation.',
    steps: [
      'Apply setup (Kp = 60, circle track), press Start.',
      'Watch the trail — the robot zigzags around the line instead of following it.',
      'Look at the Error telemetry graph — watch it swing symmetrically back and forth.',
      'Lower Kp slowly (60 → 50 → 40) until the zigzag calms down. What value works?',
      'Notice the trail changes from "wide zigzag" to "tight follow" — that is the sweet spot.',
    ],
    setup: { track: 'circle', kp: 60, ki: 0, kd: 0, base: 150 },
    highlight: ['kp', 'telemetry'],
  },
  {
    id: 'add-d',
    title: '4 · Add D — the shock absorber',
    goal: 'Use Kd to damp oscillation and smooth out corners.',
    body: 'Kd brakes when the error is changing fast — it opposes rapid swings. Adding D lets you keep a high Kp without the zigzag. PD together is the standard combination for fast robots.',
    steps: [
      'Apply setup (Kp = 40, Kd = 25, circle), press Start.',
      'Compare with lesson 3 — the zigzag is damped even though Kp is still high.',
      'Watch the D-term graph — it spikes when the error changes fast (on corners).',
      'Try Kd = 60 — the robot becomes sluggish. Too much D slows the correction.',
      'Try Kd = 10 — the zigzag returns. Find the sweet spot between 15 and 35.',
    ],
    setup: { track: 'circle', kp: 40, ki: 0, kd: 25, base: 150 },
    highlight: ['kd', 'telemetry'],
  },
  {
    id: 'sharp-corners',
    title: '5 · Sharp corners — the square track',
    goal: 'Tune PD gains to handle 90° corners without losing the line.',
    body: 'The square track has four sharp 90° corners. The robot must brake the overshoot and re-acquire the line quickly. D-term is your friend here — it fires hardest when the error spikes on a corner.',
    steps: [
      'Apply setup (square track), press Start.',
      'Watch the first corner — does the robot overshoot and lose the line?',
      'If it flies off: increase Kd. If it crawls around: increase Kp.',
      'Try Kd = 40, Kp = 45. Watch all four corners in the trail.',
      'Find the fastest base_speed where it still makes every corner cleanly.',
    ],
    setup: { track: 'square', kp: 45, ki: 0, kd: 30, base: 120 },
    highlight: ['kd'],
  },
  {
    id: 'introduce-i',
    title: '6 · Add I — the memory',
    goal: 'See how Ki fixes a persistent drift that P and D cannot fully correct.',
    body: 'If the robot keeps running slightly off-centre, a tiny steady error that P never fully eliminates. Ki accumulates past error over time and builds up a correction that pushes the robot exactly back to centre — like nudging a ship\'s rudder gradually.',
    steps: [
      'Apply setup (Ki = 2, oval), press Start.',
      'Watch the I-term graph — it grows slowly, unlike the spiky P and D terms.',
      'Let it run two full laps. Does the steady offset shrink over time?',
      'Try Ki = 10 — the integral winds up too fast and causes instability.',
      'Keep Ki small (1–4). I is a fine-trim knob, not a main driver.',
    ],
    setup: { track: 'oval', kp: 35, ki: 2, kd: 20, base: 130 },
    highlight: ['ki'],
  },
  {
    id: 'speed-up',
    title: '7 · Speed up — real tuning',
    goal: 'Combine all three terms and push for the fastest stable lap.',
    body: 'You know what each knob does. Now tune for speed: push base_speed up and re-balance Kp and Kd to keep the robot on the line. This is exactly what real line-follower tuning feels like.',
    steps: [
      'Apply setup, then push base speed to 220 and press Start.',
      'Does it stay on the oval? Adjust Kp and Kd until it does.',
      'Switch to the figure-8 track — the crossover is the hardest part.',
      'Now try the competition track at speed. What breaks first?',
      'Record your best Kp, Kd, and base. Open Code and copy your Arduino sketch.',
    ],
    setup: { track: 'oval', kp: 40, ki: 0, kd: 25, base: 200 },
    highlight: ['base', 'kp', 'kd'],
  },
]
